### ISSUE TITLE
unable to set stream resource to non-blocking - PHP 7.1 stream_set_blocking doesn't work

### ISSUE THREAD

**Issue by berbagimadani** [reactphp/stream#117] opened 2017-10-16 02:04 UTC
I am using 
-windows 7 64 bit
-php 7.1.9

PHP fatal error: uncaugt RuntimeException: unable to set stream resource to non-blocking mode in ...../vendor/react/stream/src/WritableResourceStream.php:34

look here, "stream_set_blocking doesn't work"
https://raw.githubusercontent.com/php/php-src/PHP-7.1/NEWS

please help. Thank you

**Comment by clue** [comment] 2017-10-16 07:40
Hi @berbagimadani! I'm not sure I follow what you're trying to do and what your issue is, as it's a bit unclear what you're trying to achieve from the description you've posted.

May I ask you provide a simple gist of what you're trying to achieve? Thanks!

Your referenced PHP changelog only links to https://bugs.php.net/bug.php?id=72853 which leads to https://github.com/php/php-src/commit/abe00908afa2b7227cfd601ee948ff3b57c27eb7 which is a minor fix in PHP 7.0.11 and only affects `stream_get_meta_data()` which does not appear to be relevant here.

Given you're using Windows, it looks like you may be affected by https://github.com/reactphp/stream/pull/46 and/or https://github.com/reactphp/child-process/pull/41 instead.

**Comment by berbagimadani** [comment] 2017-10-17 07:24
Thankyou for reply,
i am using -windows 7 64bit   -php 7.1.9
when i run code example "cat.php" here there is an error.
![writable-stream-error](https://user-images.githubusercontent.com/4327476/31651528-40808a36-b346-11e7-87e5-7fc90db35e5c.PNG)

I want no errors like the picture above

Thank's

**Comment by clue** [comment] 2017-10-17 07:41
Yes, this is a known issue for Windows only and is covered in our README.

Windows does not offer an API to read from console input without blocking in PHP. Unfortunately, until https://bugs.php.net/bug.php?id=47918 is addressed (which is unlikely to happen any time soon), there's nothing we could do to work around this (#46).

In order to avoid this issue: Simply don't read from console input on Windows (for example https://github.com/clue/psocksd/pull/22/commits/c2f2f90ffc8ebf8233839ba2f3553f2698930125),

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2017-10-17 07:41 UTC
Labels: help wanted, question

**Comment by merovinh** [comment] 2019-11-20 16:04
Have the same issue on Centos 7
`PHP Fatal error:  Uncaught RuntimeException: Unable to set stream resource to non-blocking mode in .../vendor/react/stream/src/WritableResourceStream.php:35`

**Comment by clue** [comment] 2019-11-20 16:55
@merovinh We're not aware of any such limitations except for process pipes on Windows. Can you create a new issue with some steps to reproduce the problem you're seeing? :+1:

**Comment by merovinh** [comment] 2019-11-20 17:16
@clue I created an issue with example here https://github.com/Kucoin/kucoin-php-sdk/issues/68

kucoin-php-sdk dependencies uses reactphp, and the problem somewhere there. Unfortunately I can't create example independent of third party.
